### ISSUE TITLE
enable cors / tile size

### ISSUE THREAD

**Issue by lhapaipai** [blacha/xyz-tile-debug#406]
Hi @blacha, thank you for your tile server !
May I suggest two features, which can be interesting.

- can you add the cors middleware to your express web server ?
- can you add the possibility to change the tileSize in the url like : 
```console
http://localhost:8855/v1/tiles/:tileMatrixSet/:tileSize/:z/:x/:y.png
http://localhost:8855/v1/tiles/WebMercatorQuad/256/10/10/10.png
```
I might also be able to contribute if you would be willing to accept help.

Thank you!

**Comment by blacha** [comment]
Howdy!

> can you add the cors middleware to your express web server ?

Yup, sure no problem! thats a good idea

> can you add the possibility to change the tileSize in the url like :

What is your use case for needing to modify the tile size?  I would have assumed most tools would just resize it to whatever tile size they needed.

I think generally the api is modified with a `@2x.png` or `@3x.png` on the end of the tile name but could be any number `@0.5x`? 

> I might also be able to contribute if you would be willing to accept help.

Happy to take PRs

**Comment by lhapaipai** [comment]
Thank you for your answer !
Maybe, tile size and scale factor both change the size but have different purpose.
in the [Mapbox doc](https://docs.mapbox.com/api/maps/static-tiles/) 

> Zoom level and tile size
> Note that 512×512 image tiles are offset by one zoom level compared to 256×256 tiles. For example, 512×512 tiles at zoom
> level 4 are equivalent to 256×256 tiles at zoom level 5.

It's details, and my use case, is only to learn how js libraries (MapBox, OpenLayers) display the tiles in their interface.
sorry it's not to build a :rocket: 

good night

**Comment by lhapaipai** [comment]
Maybe it could be an url like that :
```
"/v1/tiles/WebMercatorQuad/512/12/34/56@2x.png"
```
```js
pathToRegexp("/v1/tiles/:tms/:tilesize/:z/:x/:y(\\d+){@:factor(\\d+)x}?.png")
```

**Comment by blacha** [comment]
With mapbox / maplibre they also have a debug viewer with `map.showTileBoundaries = true` which shows which tiles are being rendered.

I think a StyleJSON/TileJSON endpoint would also be useful especially if people are working with vector and raster tiles.

Happy to add an endpoint to add a tile size, Id prefer not to change the api URL if we can avoid it, what about a `?tileSize=512` or similar?
